erp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('accounts.urls')),
    path('api/', include('data_management.urls')),
    path('api/', include('inventory_management.urls')),
    path('api/', include('sales_management.urls')),
    path('api/',include('purchase_management.urls')),
    path('', include('frontend.frontendurls'))
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import MinLengthValidator, MaxValueValidator
from django.core.exceptions import ValidationError
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.contrib.auth.hashers import make_password
from django.http import JsonResponse
from django.core.management.base import BaseCommand, CommandError
import uuid
from data_management.models import Country
# Create your models here.

from django.contrib.auth.management.commands import createsuperuser


class Branch(models.Model):
    id = models.AutoField(primary_key=True)
    cityname = models.CharField( max_length=50, null=True, blank=True)
    state = models.CharField(max_length=30, default='TamilNadu')
    country = models.ForeignKey(
        Country, on_delete=models.SET_NULL, null=True, blank=True)
    pincode = models.IntegerField(default=6000007)
    GST_Number = models.CharField(unique=True, blank=True, max_length=30)
    branch_code = models.CharField(
        editable=False, unique=True, max_length=10, null=True, blank=True, default='branchcode')
    branch_name = models.CharField(
        max_length=30, unique=True, null=True, blank=True)
    address = models.CharField(
        max_length=50, unique=True, null=True, blank=True)

    def save(self, *args, **kwargs):
        self.branch_code = str(uuid.uuid4())[:6]
        return super(Branch, self).save(*args, **kwargs)

    def __str__(self):
        return self.branch_name


class Department(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(unique=True, max_length=50)
    role = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.name


class Sub_division(models.Model):
    id = models.AutoField(primary_key=True)
    department = models.ForeignKey(
        Department, null=True, on_delete=models.SET_NULL)
    name = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.name


class UserRole(models.Model):
    id = models.AutoField(primary_key=True)
    department = models.ForeignKey(
        Department, null=True, blank=True, on_delete=models.SET_NULL)
    role = models.CharField(max_length=30, unique=True)
    division = models.ForeignKey(
        Sub_division, null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.role


class MyUserManager(BaseUserManager):
    def create_user(self, employee_id, password, name, **extra_fields):
        phone = extra_fields.get('phone', None)
        department_id = extra_fields.get('department', None)
        sub_division = extra_fields.get('department_subdivision', None)
        role = extra_fields.get('role', None)
        email = extra_fields.get('email', None)
        # employee_id = extra_fields.get('id', None)
        # name = extra_fields.get('name', None)
        if phone:
            try:
                phone = int(phone)
            except:
                raise ValueError('Mobile number only number')
        # password = make_password(password)
        # self.set_password(self.password)
        user = self.model(name=name, department=department_id, email=email,
                          phone=phone, employee_id=employee_id, department_subdivision=sub_division, role=role)
        # print(user)
        print(password)
        user.set_password(password)
        # user.save(using=self._db)
        return user

    def create_superuser(self, **extra_fields):
        user = self.create_user(**extra_fields)
        user.is_superuser = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    email = models.EmailField(unique=True, null=True, blank=True)
    employee_id = models.CharField(
        unique=True, null=False, primary_key=True, max_length=50, default=123, blank=True)
    name = models.CharField(unique=True, max_length=50)
    phone = models.CharField(
        default=1234567890,
        max_length=10,
        validators=[
            MinLengthValidator(10)
        ], null=True, blank=True)
    department = models.ForeignKey(
        Department, on_delete=models.SET_NULL, null=True, blank=True)
    department_subdivision = models.ForeignKey(
        Sub_division, on_delete=models.SET_NULL, null=True, blank=True)
    role = models.ForeignKey(UserRole, on_delete=models.SET_NULL, null=True)
    is_superuser = models.BooleanField(default=False)
    reset_password = models.BooleanField(default=True)
    branch = models.ForeignKey(Branch, on_delete=models.SET_NULL, null=True)
    created_at = models.DateTimeField(default=timezone.now)
    objects = MyUserManager()
    USERNAME_FIELD = 'employee_id'
    REQUIRED_FIELDS = ['name', 'password']

    def save(self, *args, **kwargs):
        return super(User, self).save(*args, **kwargs)

    def __str__(self):
        return self.employee_id

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        return True

    @ property
    def is_staff(self):
        return self.is_superuser

    class Meta:
        ordering = ('created_at',)

data_management/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField
from django.core.exceptions import ValidationError
# from pos
# Create your models here.


class MeasuredUnits(models.Model):
    measured_unit_code = models.CharField(
        max_length=30, primary_key=True, default='id')

    measured_unit_name = models.CharField(max_length=30, unique=True)

    def __str__(self) -> str:
        return self.measured_unit_name

    def save(self, *args, **kwargs):
        self.measured_unit_name = self.measured_unit_name .lower()
        super(MeasuredUnits, self).save(*args, **kwargs)


class Currency(models.Model):
    currency_code = models.CharField(
        max_length=30, primary_key=True, default='id')
    currency_name = models.CharField(max_length=30, unique=True)

    def __str__(self) -> str:
        return self.currency_name

    def save(self, *args, **kwargs):
        self.currency_name = self.currency_name.lower()
        super(Currency, self).save(*args, **kwargs)


class PartyType(models.Model):
    party_type = models.CharField(max_length=30, unique=True)

    class Meta:
        verbose_name = "PartyType"

    def __str__(self) -> str:
        return self.party_type

    def save(self, *args, **kwargs):
        self.party_type = self.party_type.lower()
        super(PartyType, self).save(*args, **kwargs)


class Country(models.Model):
    country_code = models.CharField(
        max_length=30, primary_key=True, default='id')
    country_name = models.CharField(max_length=30, unique=True)

    class Meta:
        verbose_name = "Country"

    def __str__(self) -> str:
        return self.country_name

    def save(self, *args, **kwargs):
        self.country_name = self.country_name.lower()
        super(Country, self).save(*args, **kwargs)


class State(models.Model):
    state_code = models.CharField(
        max_length=30, primary_key=True, default='id')
    state_name = models.CharField(max_length=30, null=True, blank=True)
    GST_code = models.CharField(max_length=30, null=True, blank=True)

    def __str__(self) -> str:
        return self.state_name


class Parties(models.Model):
    id = models.AutoField(primary_key=True)
    party_type = models.ForeignKey(
        PartyType, to_field='party_type', on_delete=models.SET_NULL, null=True)
    party_country = models.ForeignKey(
        Country, on_delete=models.SET_NULL, null=True)
    party_name = models.CharField(max_length=50)
    party_address = models.TextField()
    party_state = models.ForeignKey(
        State, on_delete=models.SET_NULL, null=True)
    party_pincode = models.IntegerField()
    party_GSTIN = models.CharField(max_length=30, null=True, blank=True)
    party_products = models.JSONField(null=True, blank=True)
    party_contact_name = models.CharField(max_length=30, null=True, blank=True)
    party_contact_no = models.CharField(max_length=30, null=True, blank=True)
    party_email = models.CharField(max_length=30, null=True, blank=True)

    class Meta:
        verbose_name = "Party"

    def clean(self):
        parties = Parties.objects.filter(
            party_name__iexact=self.party_name.lower())
        if self.pk:
            parties = parties.exclude(pk=self.pk)
        if parties.exists():
            raise ValidationError("This party already exists.")

    def __str__(self) -> str:
        return self.party_name


product_type_choices = [('finished', 'finished'),
                        ('semi-finished', 'semi-finished'),]
rm_type_choices = [('semi_finished_goods', 'semi_finished_goods'),
                   ('rawmaterial', 'Rawmaterial'),]


class ProductionPhases(models.Model):
    id = models.AutoField(primary_key=True)
    phase_name = models.CharField(max_length=100, unique=True)

    class Meta:
        verbose_name = "ProductionPhase"
        db_table = 'ProductionPhase'

    def __str__(self) -> str:
        return self.phase_name

    def save(self, *args, **kwargs):
        self.phase_name = self.phase_name.lower()
        super(ProductionPhases, self).save(*args, **kwargs)


class Product(models.Model):
    product_code = models.CharField(
        unique=True, primary_key=True, max_length=50, default='id')
    product_name = models.CharField(unique=True, max_length=100)
    product_type = models.CharField(
        max_length=50, choices=product_type_choices, default='finished')
    min_stock = models.IntegerField(default=100)
    maximum_price = models.IntegerField()
    minimum_price = models.IntegerField()
    currency = models.ForeignKey(
        Currency, on_delete=models.SET_NULL, null=True, blank=True)
    multiple_parts = models.BooleanField(default=False)
    parts = ArrayField(
        models.CharField(max_length=50, blank=True),
        blank=True,
        default=list,
        null=True
    )

    class Meta:
        verbose_name = "Product"

    def __str__(self) -> str:
        return self.product_name


class Rawmaterials(models.Model):
    rm_code = models.CharField(max_length=30, primary_key=True,)
    rm_name = models.CharField(max_length=50)
    measured_unit = models.ForeignKey(
        MeasuredUnits, on_delete=models.SET_NULL, null=True, blank=True)
    min_stock = models.IntegerField()
    rm_max_price = models.IntegerField()
    currency = models.ForeignKey(
        Currency, on_delete=models.SET_NULL, null=True, blank=True)
    preferred_supplier = ArrayField(
        models.CharField(max_length=30, null=True, blank=True),
        default=list
    )

    class Meta:
        verbose_name = "Rawmaterial"

    def __str__(self) -> str:
        return self.rm_name


class BillOfMaterials(models.Model):
    id = models.AutoField(primary_key=True)
    product_code = models.ForeignKey(Product, on_delete=models.CASCADE)
    part_name = models.CharField(max_length=30, null=True, blank=True)
    rm_serial_no = models.IntegerField(unique=True, null=True, blank=True)
    rm_type = models.CharField(
        max_length=20, choices=rm_type_choices, default='rawmaterial')
    rm_code = models.CharField(max_length=50,null=True, blank=True)
    rm_name = models.CharField(max_length=50)
    rm_quantity = models.IntegerField(null=True, blank=True)
    production_phase = models.ForeignKey(
        ProductionPhases, on_delete=models.SET_NULL, null=True, blank=True)
    measured_unit = models.ForeignKey(
        MeasuredUnits, on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        verbose_name = "BillOfMaterial"

    def save(self, *args, **kwargs):
        try:
            if self.rm_type == 'rawmaterial':
                rm = Rawmaterials.objects.get(pk=self.rm_code)
                self.rm_name = rm.rm_name
                if rm and rm.measured_unit:
                    self.measured_unit = rm.measured_unit
            else:
                rm = Product.objects.get(
                    pk=self.rm_code)
                self.rm_name = rm.product_name
        except Exception as error:
            raise ValidationError(error)
        return super(BillOfMaterials, self).save(*args, **kwargs)

    def __str__(self) -> str:
        return self.product_code.product_name + '-' + self.rm_name


class ProductionFlow(models.Model):
    id = models.AutoField(primary_key=True)
    product_code = models.ForeignKey(Product, on_delete=models.CASCADE)
    part_name = models.CharField(max_length=50, null=True, blank=True)
    phases = models.JSONField(null=True, blank=True)

    class Meta:
        verbose_name = "ProductionFlow"

    def __str__(self) -> str:
        return self.part_name


class Productivity(models.Model):
    id = models.AutoField(primary_key=True)
    phase = models.ForeignKey(
        ProductionPhases, on_delete=models.SET_NULL, null=True, blank=True)
    product = models.ForeignKey(
        Product, on_delete=models.SET_NULL, null=True, blank=True)
    part_name = models.CharField(max_length=50, null=True, blank=True)
    quantity_perday = models.PositiveIntegerField()
    scrap_quantity = models.CharField(max_length=30, null=True, blank=True)

    def __str__(self) -> str:
        return str(self.quantity_perday)

templates/inventory/goods_recipt_note.html
{% extends 'base/base.html' %}
{%load static%}
{%block content%}



<div class='messages'></div>
{%csrf_token%}
<label class='w-50 mx-3'>Goods Received From</label>
<div class='w-50'placeholder ='Goods Received From '>
    <select class='form-select w-50' id='goods_received_from' onchange='internal_transfer(this)'>
        <option value='Internal Transfer'>Internal Transfer</option>
        <option value='Contractor'>Contractor</option>
        <option value='Supplier'>Supplier</option>
    </select> 
</div>
<div  class='mx-5 my-2'id=''></div>
<div id='table'></div>
<div class='mx-5 my-2'id='contractor'></div>
<div class='mx-5 my-2'id='internal'></div>
<div class='mx-5 my-2'id='supplier'></div>
<div class='mx-5 my-2'id='transfer_request'></div>
<div class='mx-5 my-3'id='table_vlaue'></div>
<div class='mx-5 my-4' onclick='transfer_request(this)'id='internal_dropdown'></div>



<button class='btn btn-primary mx-5 my-2' id='id_submit'>Submit</button>
<a href='/inventory?model_name=sales'>Exit</a>
<button class='btn btn-primary mx-5 my-2' id='id_action'>Action</button>
<script src="{% static 'script/list_form.js'%}"></script>  
<script src="{%static 'script/inventory/goods_recipt_note.js'%}"></script>
{% endblock %}

templates/inventory/inventory-maintenance.html
{% extends 'base/base.html' %}
{% load static %}
{% block content%}
<!-- Inventory Type – Dropdown
Inventory Name – Dropdown
Warehouse/Branch - Dropdown
Stock Available -->
<div class="inventory-get-container w-50 mx-5" onchange="check_fields(this)">
    {% csrf_token %}
    <div class="messages"></div>
    <!-- <label for=""></label> -->
    <label for="inventory_type">Inventory Type</label>
    <select name="" id="inventory_type" class="form-select" onchange="get_production_data(this)">

        <option value="" selected disabled>Select Inventory Type</option>
        <option value="product">Product</option>
        <option value="rawmaterial">Raw Material</option>
    </select>
    <label for="inventory_data">Inventory Name</label>
    <select disabled name="" onchange="get_details(this)" id="inventory_data" class="form-select"></select>
    <!-- <input type="text" placeholder="ware_house_name" onchange="get_details(this)" name="" class="form-control"
        id="form_ware_house"> -->
    <label for="form_ware_house">Warehouse/Branch</label>
    <select name="" id="form_ware_house" onchange="get_details(this)" class="form-select">
        <option value="" selected disabled>Select Warehouse/Branch</option>
    </select>
    <label for="form_stock">Stock Available</label>
    <input type="number" name="" class="form-control" id="form_stock">
</div>
<button type="submit" onclick="submit_data(null)" id="submit_button" disabled>Create</button>
<a href="" id="inventory-url">Exit</a>
<script src="{% static 'script/inventory/inventory-maintenance.js' %}"></script>

{% endblock %}

templates/inventory/inventory-menu.html
{% extends 'base/base.html' %}
{% load static %}
{% block content%}
<div class="inventory-menu d-flex flex-row justify-content-center flex-wrap mt-5"></div>
<script src="{% static 'script/inventory/inventory-menu.js' %}"></script>
{% endblock %}

templates/inventory/inventorytransfer.html
{%extends 'base/base.html'%}
{%load static%}
{%block content%}
<div class='messages'></div>
<label for="transfer_type">Transfer Type </label>
<div class="d-flex flex-wrap w-75">
    <select id="transfer_type" class="form-select w-75" onchange="inventory_type(this)">
        <option selected disabled value="">Select Transfer type</option>
        <option value="internal transfer">internal transfer</option>
        <option value="jobwork">jobwork</option>
    </select>
    <label class='my-1 w-50' for='send_to_party'>Send to Party </label>
    <div class='branch w-75'>
        <select class='form-control my-3' id='id_branch'>
            <option value=''>Select Party</option>
        </select>
    </div>
    <div class='w-75' id='id_options'>
        <label>Product_type</label>
        <select class='w-50 form-select' id='Product_type' placeholder='Product_type'
            onchange='product_dropdowns(this)'>
            <option selected disabled value="">Select raw material type</option>
            <option value='Finished Goods'>Finished Goods</option>
            <option value='Semi-finished Goods'>Semi-finished Goods</option>
            <option value='Raw materials/Accessories'>Raw materials/Accessories</option>
        </select>
        <label class='w-50'>Product_name</label>
        <select class='w-50 form-select' oninput="get_bom(this)" id='Product_name' placeholder='Product_name'>
            <option value=''></option>
        </select>
        <label class='w-50 my-2'>quantity</label>
        <input class='w-50 my-2' id='quantity' placeholder='quanity' onchange='product_get()'></input>
    </div>
    <div id="party_data"></div>
    <div id="bilofmaterial"></div>
    <div class='w-3' id='party_type'></div>

    <div id='vehicle_details'>
        <label class='my-2 w-50'>vehicle_type</label>
        <input class="vehicle_type" placeholder='vehicle_type'><br>
        <label class='my-2 w-50'>vehicle_number</label>
        <input class="vehicle_number " placeholder='vehicle_number'>
    </div>

    <div class="d-flex flex-wrap w-75">
        <label>Freightcharges</label>
        <select id="Freight_charges" class="form-select" placeholder="Freight Charges paid by">
            <option value="Self">Self</option>
            <option value="other_party">other party </option>
        </select>
    </div>
    <div class='w-3' id="transfer"></div>
    <label class='my-2 w-50'>Freight Charges Amount</label>
    <input type="number" class="form-control" placeholder="Freight Charges Amount" id="Freight_Charges_Amount">

    <!-- {% comment %} < class="form-select" name="transporter_details"> {% endcomment %} -->
    <label for="Transporter_details">Transporter details</label>
    <select class='form-select' id="Transporter_details">
        <option value=''></option>
    </select>
    <button class="btn btn-primary btn-sm w-25 my-3 " onclick="submiton(this)">submit</button>
    <a href="/inventory?model_name=inventory" id="">exit</a>
    <button class="btn btn-primary btn-sm w-25 mx-3 my-3 float-right" onclick="">Action</button>
    <script src="{% static 'script/list_form.js'%}"></script>
    <script src="{% static 'script/inventory/inventorytransfer.js'%}"></script>
    {%endblock%}

templates/inventory/manualdeliverynote.html
{% extends 'base/base.html'%}
{% load static %}



{% block content %}
<div class ='manualdelivery_container w-50 mx-5'></div>
{%csrf_token%}
<div class='message'></div>
<input class='form-control' type='number' placeholder='salesorder_number' id='id_salesdorder'>
<button type='submit' onclick="submit()"class="btn btn-primary" id='salesordernumber'>submit</button>
<script src="{% static 'script/inventory/manualdeliverynote.js' %}"></script>
{% endblock %}













templates/inventory/new_purchase_request.html
{% extends 'base/base.html' %}
{% load static %}
{% block content%}

<div id="messages"></div>
<div id="purchase_request_form">

</div>
<input type="submit" onclick="submit_pr()" disabled id="pr_submit_button" value="Submit">
<script src="{% static 'script/purchase_request.js' %}"></script>
{% endblock %}

templates/inventory/newproduction.html
{% extends 'base/base.html' %}
<!-- {% load static %} -->
{% block content %}
<div class="inventory-get-container w-50 mx-5" onchange="check_fields(this)"></div>
{% csrf_token %}
<div class="messages"></div>
<select name="" id="production_type" class="form-select" onchange="get_production_data(this)">
    <option value="" selected disabled>Select product Type</option>
    <option value="saledorder">salesorder</option>
    <option value="internal">internal</option>
</select>
<input type="number" name="" placeholder="sales_order_number" class="form-control" id="id_sales_order">
<label for="exampleInputEmail1">Product</label>
<select class="form-select" onchange="get_bom(this)" id="id_product">
    <option value=""></option>

</select>
<input type="number" placeholder="quantity" class="form-control" id="id_quantity">
<button type="submit" onclick="submit()" class="btn btn-primary" id="product_submit">Submit</button>
</div>
</div>
<div class='billofmaterial'></div>
</div>
<script src="{% static 'script/newproduction.js' %}"></script>
{% endblock %}

templates/inventory/production-order.html
{% extends 'base/base.html' %}
{% load static %}
{% block content%}
<div class="messages"></div>
<div class="production-order-list"></div>
<div id="production-order-form" class="w-50"></div>
<div class="submit-button">
</div>
<script src="{% static 'script/inventory/production-order.js' %}"></script>
<script src="{% static 'script/inventory/production-order-post.js' %}"></script>
{% endblock %}

templates/inventory/purchase-request.html
{% extends 'base/base.html' %}
{% load static %}
{% block content%}

<div class="messages"></div>
<!-- <div class="production-order-list"></div> -->
<div id="pr-form" class="w-50"></div>
<div id="submit-btn">
</div>
<script src="{% static 'script/inventory/purchase-request.js' %}"></script>
{% endblock %}

templates/inventory/return-goods.html
{% extends 'base/base.html' %}
{% load static %}
{% block content%}

<div id="messages"></div>
<div id="purchase_request_form">

</div>
<input type="submit" onclick="submit_return_goods()" disabled id="pr_submit_button" value="Submit">
<script src="{% static 'script/inventory/returngoods.js' %}"></script>
{% endblock %}

templates/inventory/return_goods.html
{% extends 'base/base.html' %}
{% load static %}
{% block content%}

<div id="messages"></div>
<div>
<label class='w-50 my-0 mx-3 '>Sales Order No</label>
<input class="form-control w-50" id='id_salesorder' onchange='sales_order(this)'type="text" placeholder='Sales Order No'></div>
<label class='w-50 my-0 mx-5'>Sales Invoice No</label>
<div class = 'w-50 mx-5'>
    <select  class = 'form-select my-2' id='sales_invoice_no' onchange='sales_invoice_no()'>
       <option value=''></option>
     </select></div>


     <div class='w-50 mx-5' id='sales_order_list'></div>

     <div class='w-50 mx-5' id='table'></div>

<div class='w-50 mx-5' id='customer_details'>
   <label>customer_details</label><br>
  </div>
<div class='w-50 mx-5'id='details'></div>
{% comment %} <div class='w-50 mx-5' id='customer'></div>  {% endcomment %}
<div class='w-50 mx-5' id='branch'></div>

<div class='w-50 mx-5' id='tabel'></div>

<button class="btn btn-primary mx-5 my-2" id='id_submit'>submit</button>
<button><a href="/inventory?model_name=inventory">Exit</a></button>
<button class="btn btn-primary mx-5" id='id_submit'>Action</button>

<script src="{% static 'script/list_form.js'%}"></script>  
<script src="{% static 'script/inventory/returngoods.js' %}"></script>
{% endblock %}