erp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('accounts.urls')),
    path('api/', include('data_management.urls')),
    path('api/', include('inventory_management.urls')),
    path('api/', include('sales_management.urls')),
    path('api/',include('purchase_management.urls')),
    path('', include('frontend.frontendurls'))
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

data_management/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField
from django.core.exceptions import ValidationError
# from pos
# Create your models here.


class MeasuredUnits(models.Model):
    measured_unit_code = models.CharField(
        max_length=30, primary_key=True, default='id')

    measured_unit_name = models.CharField(max_length=30, unique=True)

    def __str__(self) -> str:
        return self.measured_unit_name

    def save(self, *args, **kwargs):
        self.measured_unit_name = self.measured_unit_name .lower()
        super(MeasuredUnits, self).save(*args, **kwargs)


class Currency(models.Model):
    currency_code = models.CharField(
        max_length=30, primary_key=True, default='id')
    currency_name = models.CharField(max_length=30, unique=True)

    def __str__(self) -> str:
        return self.currency_name

    def save(self, *args, **kwargs):
        self.currency_name = self.currency_name.lower()
        super(Currency, self).save(*args, **kwargs)


class PartyType(models.Model):
    party_type = models.CharField(max_length=30, unique=True)

    class Meta:
        verbose_name = "PartyType"

    def __str__(self) -> str:
        return self.party_type

    def save(self, *args, **kwargs):
        self.party_type = self.party_type.lower()
        super(PartyType, self).save(*args, **kwargs)


class Country(models.Model):
    country_code = models.CharField(
        max_length=30, primary_key=True, default='id')
    country_name = models.CharField(max_length=30, unique=True)

    class Meta:
        verbose_name = "Country"

    def __str__(self) -> str:
        return self.country_name

    def save(self, *args, **kwargs):
        self.country_name = self.country_name.lower()
        super(Country, self).save(*args, **kwargs)


class State(models.Model):
    state_code = models.CharField(
        max_length=30, primary_key=True, default='id')
    state_name = models.CharField(max_length=30, null=True, blank=True)
    GST_code = models.CharField(max_length=30, null=True, blank=True)

    def __str__(self) -> str:
        return self.state_name


class Parties(models.Model):
    id = models.AutoField(primary_key=True)
    party_type = models.ForeignKey(
        PartyType, to_field='party_type', on_delete=models.SET_NULL, null=True)
    party_country = models.ForeignKey(
        Country, on_delete=models.SET_NULL, null=True)
    party_name = models.CharField(max_length=50)
    party_address = models.TextField()
    party_state = models.ForeignKey(
        State, on_delete=models.SET_NULL, null=True)
    party_pincode = models.IntegerField()
    party_GSTIN = models.CharField(max_length=30, null=True, blank=True)
    party_products = models.JSONField(null=True, blank=True)
    party_contact_name = models.CharField(max_length=30, null=True, blank=True)
    party_contact_no = models.CharField(max_length=30, null=True, blank=True)
    party_email = models.CharField(max_length=30, null=True, blank=True)

    class Meta:
        verbose_name = "Party"

    def clean(self):
        parties = Parties.objects.filter(
            party_name__iexact=self.party_name.lower())
        if self.pk:
            parties = parties.exclude(pk=self.pk)
        if parties.exists():
            raise ValidationError("This party already exists.")

    def __str__(self) -> str:
        return self.party_name


product_type_choices = [('finished', 'finished'),
                        ('semi-finished', 'semi-finished'),]
rm_type_choices = [('semi_finished_goods', 'semi_finished_goods'),
                   ('rawmaterial', 'Rawmaterial'),]


class ProductionPhases(models.Model):
    id = models.AutoField(primary_key=True)
    phase_name = models.CharField(max_length=100, unique=True)

    class Meta:
        verbose_name = "ProductionPhase"
        db_table = 'ProductionPhase'

    def __str__(self) -> str:
        return self.phase_name

    def save(self, *args, **kwargs):
        self.phase_name = self.phase_name.lower()
        super(ProductionPhases, self).save(*args, **kwargs)


class Product(models.Model):
    product_code = models.CharField(
        unique=True, primary_key=True, max_length=50, default='id')
    product_name = models.CharField(unique=True, max_length=100)
    product_type = models.CharField(
        max_length=50, choices=product_type_choices, default='finished')
    min_stock = models.IntegerField(default=100)
    maximum_price = models.IntegerField()
    minimum_price = models.IntegerField()
    currency = models.ForeignKey(
        Currency, on_delete=models.SET_NULL, null=True, blank=True)
    multiple_parts = models.BooleanField(default=False)
    parts = ArrayField(
        models.CharField(max_length=50, blank=True),
        blank=True,
        default=list,
        null=True
    )

    class Meta:
        verbose_name = "Product"

    def __str__(self) -> str:
        return self.product_name


class Rawmaterials(models.Model):
    rm_code = models.CharField(max_length=30, primary_key=True,)
    rm_name = models.CharField(max_length=50)
    measured_unit = models.ForeignKey(
        MeasuredUnits, on_delete=models.SET_NULL, null=True, blank=True)
    min_stock = models.IntegerField()
    rm_max_price = models.IntegerField()
    currency = models.ForeignKey(
        Currency, on_delete=models.SET_NULL, null=True, blank=True)
    preferred_supplier = ArrayField(
        models.CharField(max_length=30, null=True, blank=True),
        default=list
    )

    class Meta:
        verbose_name = "Rawmaterial"

    def __str__(self) -> str:
        return self.rm_name


class BillOfMaterials(models.Model):
    id = models.AutoField(primary_key=True)
    product_code = models.ForeignKey(Product, on_delete=models.CASCADE)
    part_name = models.CharField(max_length=30, null=True, blank=True)
    rm_serial_no = models.IntegerField(unique=True, null=True, blank=True)
    rm_type = models.CharField(
        max_length=20, choices=rm_type_choices, default='rawmaterial')
    rm_code = models.CharField(max_length=50,null=True, blank=True)
    rm_name = models.CharField(max_length=50)
    rm_quantity = models.IntegerField(null=True, blank=True)
    production_phase = models.ForeignKey(
        ProductionPhases, on_delete=models.SET_NULL, null=True, blank=True)
    measured_unit = models.ForeignKey(
        MeasuredUnits, on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        verbose_name = "BillOfMaterial"

    def save(self, *args, **kwargs):
        try:
            if self.rm_type == 'rawmaterial':
                rm = Rawmaterials.objects.get(pk=self.rm_code)
                self.rm_name = rm.rm_name
                if rm and rm.measured_unit:
                    self.measured_unit = rm.measured_unit
            else:
                rm = Product.objects.get(
                    pk=self.rm_code)
                self.rm_name = rm.product_name
        except Exception as error:
            raise ValidationError(error)
        return super(BillOfMaterials, self).save(*args, **kwargs)

    def __str__(self) -> str:
        return self.product_code.product_name + '-' + self.rm_name


class ProductionFlow(models.Model):
    id = models.AutoField(primary_key=True)
    product_code = models.ForeignKey(Product, on_delete=models.CASCADE)
    part_name = models.CharField(max_length=50, null=True, blank=True)
    phases = models.JSONField(null=True, blank=True)

    class Meta:
        verbose_name = "ProductionFlow"

    def __str__(self) -> str:
        return self.part_name


class Productivity(models.Model):
    id = models.AutoField(primary_key=True)
    phase = models.ForeignKey(
        ProductionPhases, on_delete=models.SET_NULL, null=True, blank=True)
    product = models.ForeignKey(
        Product, on_delete=models.SET_NULL, null=True, blank=True)
    part_name = models.CharField(max_length=50, null=True, blank=True)
    quantity_perday = models.PositiveIntegerField()
    scrap_quantity = models.CharField(max_length=30, null=True, blank=True)

    def __str__(self) -> str:
        return str(self.quantity_perday)

sales_management/models.py
from django.db import models
from data_management.models import Parties, Product, Currency
from accounts.models import User


status_choices = [('new', 'new'),
                  ('completed', 'completed'),
                  ('cancelled', 'cancelled'),
                  ('modified', 'modified')]

freight_charges_paid_by_choices = [('self', 'self'),
                                   ('customer', 'customer')]


class Sales_order(models.Model):
    sales_order_no = models.AutoField(primary_key=True)
    sales_order_date = models.DateField(auto_now_add=True)
    customer_id = models.ForeignKey(
        Parties, on_delete=models.SET_NULL, null=True)
    sales_person_id = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True)
    date_delivery_expected = models.DateField()
    status = models.CharField(
        max_length=20, choices=status_choices, default=status_choices[0])
    returnedgoods = models.JSONField(null=True,blank=True)

    class Meta:
        verbose_name = 'sales_order'

    def __str__(self):
        return str(self.sales_order_no)


class Sales_order_items(models.Model):
    sales_order_no = models.ForeignKey(
        Sales_order, on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(
        Product, on_delete=models.SET_NULL, null=True)
    quantity_ordered = models.IntegerField()
    unit_price = models.IntegerField(null=True, blank=True)
    currency = models.ForeignKey(
        Currency, on_delete=models.SET_NULL, null=True, blank=True)
    gst = models.IntegerField(null=True, blank=True)
    freight_charges = models.IntegerField(null=True, blank=True)
    freight_charges_paid_by = models.CharField(
        max_length=20, choices=freight_charges_paid_by_choices, default="self")
    total_price = models.IntegerField(null=True, blank=True)
    # Freight Charges Paid by
    payment_terms = models.CharField(max_length=50)
    due_date = models.DateField(null=True, blank=True)
    units_delivered = models.IntegerField(null=True, blank=True)
    date_delivery_expected = models.DateField(null=True, blank=True)

    class Meta:
        verbose_name = 'sales_order_items'

    def __str__(self):
        return str(self.sales_order_no)


class Delivery_note(models.Model):
    sales_order_no = models.ForeignKey(
        Sales_order, on_delete=models.SET_NULL, null=True)
    product_id = models.ForeignKey(
        Product, on_delete=models.SET_NULL, null=True)
    date_delivery = models.DateField()
    delivery_mode = models.CharField(max_length=50)
    delivery_details = models.JSONField(null=True, blank=True)
    units_delivered = models.IntegerField()
    eway_bill_no = models.CharField(max_length=50)

    class Meta:
        verbose_name = 'delivery_note'

    def __str__(self):
        return self.sales_order_no + '-' + self.date_delivery


class Sales_invoice(models.Model):
    sales_invoice_no = models.CharField(max_length=50)
    sales_order_no = models.ForeignKey(
        Sales_order, on_delete=models.SET_NULL, null=True)
    e_invoice_no = models.CharField(max_length=30)

    class Meta:
        verbose_name = 'sales_invoice'

    def __str__(self):
        return self.sales_invoice_no


class Returned_goods(models.Model):
    return_reciept_no = models.AutoField(primary_key=True)
    return_reciept_date = models.DateField(null=True)
    sales_invoice = models.ForeignKey(
        Sales_invoice, on_delete=models.SET_NULL, null=True)
    sales_order_no = models.ForeignKey(
        Sales_order, on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(
        Product, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField(null=True)
    return_reason = models.CharField(max_length=50)
    returned_goods_status = models.CharField(max_length=50)

    class Meta:
        verbose_name = 'returned_goods'

    def __str__(self):
        return self.sales_order_no

templates/base/admin.html
{% extends 'base/base.html'%}
{% block content %}



<div class="d-flex flex-row justify-content-center admin_page_conytainer flex-wrap mt-5">
</div>
<script>
    let url = new URLSearchParams(window.location.search)
    // console.log(url,'urk',url.get('model_name'))
    page_name = url.get('content')
    console.log(page_name, 'pagge')
    admin_page_data = { 'data-management': ['product', 'rawmaterial', 'bill of material', 'production flow', 'parties'], 'user-management': ['branch', 'department', 'sub division', 'user role', 'user'], 'settings': ['production phase', 'country', 'party type'] }
    content = ''
    host = window.location.protocol + "//" + window.location.host;
    admin_page_data[page_name].forEach(element => {
        element_name = element.replace(/ /g, '')
        if (page_name == 'data-management') {
            content += ` <a href="${host}/${element_name}" class="nav-link text-truncate" id="${element_name}">
        <div class="card mx-2 my-5 p-5 ">${element}</div>
    </a>`
        }
        else {
            content += ` <a href="${host}/data-management/?model_name=${element_name}" class="nav-link text-truncate" id="${element}">
        <div class="card mx-2 my-5 p-5 ">${element}</div>
    </a>`
        }

    });
    document.querySelector('.admin_page_conytainer').innerHTML = content

    // console.log(content, 'cont')
    // if (page_name == 'data-management') {
    //     document.getElementById("rawmaterial").href = `${host}/rawmaterial`
    //     document.getElementById("bill of material").href = `${host}/billofmaterial`
    //     document.getElementById("product").href = `${host}/product`
    //     document.getElementById("production flow").href = `${host}/productionflow`
    //     document.getElementById("parties_url").href = `${host}/parties`
    // } else if (page_name == 'user-management') {

    //     document.getElementById("branch_url").href = `${host}/data-management/?model_name=branch`
    //     document.getElementById("department_url").href = `${host}/data-management/?model_name=department`
    //     document.getElementById("user_role_url").href = `${host}/data-management/?model_name=userrole`
    //     document.getElementById("division_url").href = `${host}/data-management/?model_name=subdivition`
    //     document.getElementById('user_url').href = `${host}/data-management/?model_name=user`
    // } else if (page_name == 'settings') {
    //     document.getElementById("partytype").href = `${host}/data-management/?model_name=partytype`
    //     document.getElementById("country").href = `${host}/data-management/?model_name=country`
    //     document.getElementById("phase").href = `${host}/data-management/?model_name=productionphase`
    //     document.getElementById("phase_url").href = `${host}/data-management/?model_name=productionphase`

    // }
</script>
{% endblock %}

templates/base/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <!-- icon -->
    <link rel="icon" href="{% static 'media/management.png' %}">
    <link rel="stylesheet" href="{% static 'styles/front-end.css' %}">

    <!--  -->
    <title>ERP</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles/base.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"></script>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
        integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600&family=Poppins:wght@500;600&display=swap"
        rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
    <p class="csrf">{% csrf_token %}</p>
    <script src="{% static 'script/data/form.js' %}"></script>
    <script src="{% static 'script/main.js' %}"></script>


    {% block content %}
    {% endblock %}

    <script>
        // let length = history.length;

        // console.log(length);
        // var host = window.location.protocol + "//" + window.location.host;
        // if (window.location.href == `${host}/main/`) {
        //     document.getElementById("backbutton").style.display = "none";
        // }
        // else {
        //     document.getElementById("backbutton").style.display = "block";
        // }
        // function backButton() {

        //     window.history.back();

        // }
    </script>
</body>


</html>

templates/base/main.html
{% extends 'base.html' %}
{% block content %}
{% endblock %}
<div class="modal fade" id="BillofMaterialModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Add Bill Of Material</h5>
                <button type="button" class="close btn bg-none" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="messages"></div>
                <div class="d-flex  justify-content-center">
                    {% csrf_token %}
                    <div class="form-group d-flex">
                        <label for="exampleInputEmail1">Serial No</label>
                        <input type="text" class="form-control my-3" id="id_serial_no" placeholder="Enter Serial No">
                        <label for="exampleInputEmail1">Quantity</label>
                        <input type="text" class="form-control my-3" id="id_quantity" placeholder="Enter  Quantity">
                        <label for="exampleInputEmail1">Measured Unit</label>
                        <input type="text" class="form-control my-3" id="id_measured_unit" placeholder="Enter unit">
                        <label for="exampleInputEmail1">Product</label>
                        <select class="form-control my-3" id="id_product">
                            <option value=""></option>
                        </select>
                        <label for="exampleInputEmail1">Raw Material</label>
                        <select class="form-control my-3" id="id_rawmaterial">
                            <option value=""></option>
                        </select>


                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary" id="BillofMaterialButton">Submit</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Delete</h5>
                <button type="button" class="close btn bg-none" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Are your sure to delete ?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="yes">Yes</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
            </div>
        </div>
    </div>
</div>

templates/base/nd.html
<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvas" data-bs-keyboard="false" data-bs-backdrop="false">
    <div class="offcanvas-header">
        <h6 class="offcanvas-title d-none d-sm-block" id="offcanvas">Menu</h6>
        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body px-0">
        <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-start" id="menu">
            <li class="nav-item">
                <a href="#" class="nav-link text-truncate">
                    <i class="fs-5 bi-house"></i><span class="ms-1 d-none d-sm-inline">Home</span>
                </a>
            </li>
            <li>
                <a href="#submenu1" data-bs-toggle="collapse" class="nav-link text-truncate">
                    <i class="fs-5 bi-speedometer2"></i><span class="ms-1 d-none d-sm-inline">Dashboard</span> </a>
            </li>

            <li>
                <a href="#" id="sales-url-nav" class="nav-link text-truncate">
                    <i class="fs-5 bi-table"></i><span class="ms-1 d-none d-sm-inline">sales-management</span></a>
            </li>

            <li class="admin">
                <a href="#" data-bs-toggle="dropdown" class="nav-link dropdown-toggle  text-truncate"
                    aria-expanded="false">
                    <i class="fs-5 bi-speedometer2"></i><span class="ms-1 d-none d-sm-inline">Admin</span> </a>
                <ul class="dropdown-menu text-small shadow" aria-labelledby="admin">
                    <li><a class="dropdown-item" id="data-management-url" href="#">Data Management</a></li>
                    <hr class="dropdown-divider">
                    <li><a class="dropdown-item" id="user-management-url" href="#">Manage users</a></li>
                    <hr class="dropdown-divider">
                    <li><a class="dropdown-item" id="settings-url" href="#">Settings</a></li>
                </ul>
            </li>


            <li>
                <a href="#" id="inventory-url-nav" class="nav-link text-truncate">
                    <i class="fs-5 bi-people"></i><span class="ms-1 d-none d-sm-inline">inventory</span> </a>
            </li>
            <li>
                <a href="#" id="production-url-nav" class="nav-link text-truncate">
                    <i class="fs-5 bi-people"></i><span class="ms-1 d-none d-sm-inline">production</span> </a>
            </li>
        </ul>
    </div>
</div>

<div class="navbar-container"></div>

<button class="btn float-start" data-bs-toggle="offcanvas" data-bs-target="#offcanvas" role="button">
    <i class="bi bi-arrow-right-square-fill fs-3" data-bs-toggle="offcanvas" data-bs-target="#offcanvas"></i>
</button>

<script>
    var host = window.location.protocol + "//" + window.location.host;
    // document.getElementById('admin').href = `${host}/admindash`
    document.getElementById('data-management-url').href = `${host}/admindashboard/?content=data-management`
    document.getElementById('user-management-url').href = `${host}/admindashboard/?content=user-management`
    document.getElementById('settings-url').href = `${host}/admindashboard/?content=settings`
    document.getElementById('inventory-url-nav').href = `${host}/inventory?model_name=inventory`
    document.getElementById('sales-url-nav').href = `${host}/inventory?model_name=sales-order`
    document.getElementById('production-url-nav').href = `${host}/inventory?model_name=production`
</script>

templates/base/title-header.html
<div id="header" class="header">
    <div class="logo">
        <img src="/media/assets/header/logo.svg" />
    </div>
    <div class="settings-notify">
        <div class="settings-notify-img">
            <img class="notify-img" src="/media/assets/header/notification.svg" />
            <img class="settings-img" src="/media/assets/header/settings.svg" />

        </div>
    </div>
    <div class="header-content">
        <p class="page_name" id="page_name"></p>
        <div class="bread-crum-div" id="dm-bread-crum"></div>
        <div class="dm-add-button-div"></div>
    </div>
    <!-- sd -->
</div>