erp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('accounts.urls')),
    path('api/', include('data_management.urls')),
    path('api/', include('inventory_management.urls')),
    path('api/', include('sales_management.urls')),
    path('api/',include('purchase_management.urls')),
    path('', include('frontend.frontendurls'))
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

data_management/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField
from django.core.exceptions import ValidationError
# from pos
# Create your models here.


class MeasuredUnits(models.Model):
    measured_unit_code = models.CharField(
        max_length=30, primary_key=True, default='id')

    measured_unit_name = models.CharField(max_length=30, unique=True)

    def __str__(self) -> str:
        return self.measured_unit_name

    def save(self, *args, **kwargs):
        self.measured_unit_name = self.measured_unit_name .lower()
        super(MeasuredUnits, self).save(*args, **kwargs)


class Currency(models.Model):
    currency_code = models.CharField(
        max_length=30, primary_key=True, default='id')
    currency_name = models.CharField(max_length=30, unique=True)

    def __str__(self) -> str:
        return self.currency_name

    def save(self, *args, **kwargs):
        self.currency_name = self.currency_name.lower()
        super(Currency, self).save(*args, **kwargs)


class PartyType(models.Model):
    party_type = models.CharField(max_length=30, unique=True)

    class Meta:
        verbose_name = "PartyType"

    def __str__(self) -> str:
        return self.party_type

    def save(self, *args, **kwargs):
        self.party_type = self.party_type.lower()
        super(PartyType, self).save(*args, **kwargs)


class Country(models.Model):
    country_code = models.CharField(
        max_length=30, primary_key=True, default='id')
    country_name = models.CharField(max_length=30, unique=True)

    class Meta:
        verbose_name = "Country"

    def __str__(self) -> str:
        return self.country_name

    def save(self, *args, **kwargs):
        self.country_name = self.country_name.lower()
        super(Country, self).save(*args, **kwargs)


class State(models.Model):
    state_code = models.CharField(
        max_length=30, primary_key=True, default='id')
    state_name = models.CharField(max_length=30, null=True, blank=True)
    GST_code = models.CharField(max_length=30, null=True, blank=True)

    def __str__(self) -> str:
        return self.state_name


class Parties(models.Model):
    id = models.AutoField(primary_key=True)
    party_type = models.ForeignKey(
        PartyType, to_field='party_type', on_delete=models.SET_NULL, null=True)
    party_country = models.ForeignKey(
        Country, on_delete=models.SET_NULL, null=True)
    party_name = models.CharField(max_length=50)
    party_address = models.TextField()
    party_state = models.ForeignKey(
        State, on_delete=models.SET_NULL, null=True)
    party_pincode = models.IntegerField()
    party_GSTIN = models.CharField(max_length=30, null=True, blank=True)
    party_products = models.JSONField(null=True, blank=True)
    party_contact_name = models.CharField(max_length=30, null=True, blank=True)
    party_contact_no = models.CharField(max_length=30, null=True, blank=True)
    party_email = models.CharField(max_length=30, null=True, blank=True)

    class Meta:
        verbose_name = "Party"

    def clean(self):
        parties = Parties.objects.filter(
            party_name__iexact=self.party_name.lower())
        if self.pk:
            parties = parties.exclude(pk=self.pk)
        if parties.exists():
            raise ValidationError("This party already exists.")

    def __str__(self) -> str:
        return self.party_name


product_type_choices = [('finished', 'finished'),
                        ('semi-finished', 'semi-finished'),]
rm_type_choices = [('semi_finished_goods', 'semi_finished_goods'),
                   ('rawmaterial', 'Rawmaterial'),]


class ProductionPhases(models.Model):
    id = models.AutoField(primary_key=True)
    phase_name = models.CharField(max_length=100, unique=True)

    class Meta:
        verbose_name = "ProductionPhase"
        db_table = 'ProductionPhase'

    def __str__(self) -> str:
        return self.phase_name

    def save(self, *args, **kwargs):
        self.phase_name = self.phase_name.lower()
        super(ProductionPhases, self).save(*args, **kwargs)


class Product(models.Model):
    product_code = models.CharField(
        unique=True, primary_key=True, max_length=50, default='id')
    product_name = models.CharField(unique=True, max_length=100)
    product_type = models.CharField(
        max_length=50, choices=product_type_choices, default='finished')
    min_stock = models.IntegerField(default=100)
    maximum_price = models.IntegerField()
    minimum_price = models.IntegerField()
    currency = models.ForeignKey(
        Currency, on_delete=models.SET_NULL, null=True, blank=True)
    multiple_parts = models.BooleanField(default=False)
    parts = ArrayField(
        models.CharField(max_length=50, blank=True),
        blank=True,
        default=list,
        null=True
    )

    class Meta:
        verbose_name = "Product"

    def __str__(self) -> str:
        return self.product_name


class Rawmaterials(models.Model):
    rm_code = models.CharField(max_length=30, primary_key=True,)
    rm_name = models.CharField(max_length=50)
    measured_unit = models.ForeignKey(
        MeasuredUnits, on_delete=models.SET_NULL, null=True, blank=True)
    min_stock = models.IntegerField()
    rm_max_price = models.IntegerField()
    currency = models.ForeignKey(
        Currency, on_delete=models.SET_NULL, null=True, blank=True)
    preferred_supplier = ArrayField(
        models.CharField(max_length=30, null=True, blank=True),
        default=list
    )

    class Meta:
        verbose_name = "Rawmaterial"

    def __str__(self) -> str:
        return self.rm_name


class BillOfMaterials(models.Model):
    id = models.AutoField(primary_key=True)
    product_code = models.ForeignKey(Product, on_delete=models.CASCADE)
    part_name = models.CharField(max_length=30, null=True, blank=True)
    rm_serial_no = models.IntegerField(unique=True, null=True, blank=True)
    rm_type = models.CharField(
        max_length=20, choices=rm_type_choices, default='rawmaterial')
    rm_code = models.CharField(max_length=50,null=True, blank=True)
    rm_name = models.CharField(max_length=50)
    rm_quantity = models.IntegerField(null=True, blank=True)
    production_phase = models.ForeignKey(
        ProductionPhases, on_delete=models.SET_NULL, null=True, blank=True)
    measured_unit = models.ForeignKey(
        MeasuredUnits, on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        verbose_name = "BillOfMaterial"

    def save(self, *args, **kwargs):
        try:
            if self.rm_type == 'rawmaterial':
                rm = Rawmaterials.objects.get(pk=self.rm_code)
                self.rm_name = rm.rm_name
                if rm and rm.measured_unit:
                    self.measured_unit = rm.measured_unit
            else:
                rm = Product.objects.get(
                    pk=self.rm_code)
                self.rm_name = rm.product_name
        except Exception as error:
            raise ValidationError(error)
        return super(BillOfMaterials, self).save(*args, **kwargs)

    def __str__(self) -> str:
        return self.product_code.product_name + '-' + self.rm_name


class ProductionFlow(models.Model):
    id = models.AutoField(primary_key=True)
    product_code = models.ForeignKey(Product, on_delete=models.CASCADE)
    part_name = models.CharField(max_length=50, null=True, blank=True)
    phases = models.JSONField(null=True, blank=True)

    class Meta:
        verbose_name = "ProductionFlow"

    def __str__(self) -> str:
        return self.part_name


class Productivity(models.Model):
    id = models.AutoField(primary_key=True)
    phase = models.ForeignKey(
        ProductionPhases, on_delete=models.SET_NULL, null=True, blank=True)
    product = models.ForeignKey(
        Product, on_delete=models.SET_NULL, null=True, blank=True)
    part_name = models.CharField(max_length=50, null=True, blank=True)
    quantity_perday = models.PositiveIntegerField()
    scrap_quantity = models.CharField(max_length=30, null=True, blank=True)

    def __str__(self) -> str:
        return str(self.quantity_perday)

templates/dmtemplates/billofmaterials.html
{% extends 'base/base.html' %}
{% load static %}
{% block content%}
<div class="messages"></div>
<!-- Modal -->

<div class="d-flex flex-row justify-content-center flex-wrap mt-5" id="rawmaterialdiv">
        <div class="card mx-2 my-5 p-5" id="showform">Add New</div>
        <div class="card mx-2 my-5 p-5" id="rawmaterialtable">Existing</div>
</div>
<div class="fill-message">
        <p class="text-center"> Fill all the detail to add new row </p>
</div>

<div id="product_div"></div>
{% include 'dmtemplates/billofmaterialstable.html' %}
<script src="{% static 'script/list_form.js' %}"></script>
{% endblock %}

templates/dmtemplates/billofmaterialstable.html
{% csrf_token %}
{% load static %}
<div class="modal fade" id="BillofMaterialModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Add Bill Of Material</h5>
                <button type="button" class="close btn bg-none" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="messages"></div>
                <div class="d-flex flex-row justify-content-center">
                    {% csrf_token %}
                    <div class="form-group">

                        <label for="exampleInputEmail1">Serial No</label>
                        <input type="text" class="form-control my-3" id="form_rm_serial_no"
                            placeholder="Enter Serial No">
                        <label for="exampleInputEmail1">Quantity</label>
                        <input type="text" class="form-control my-3" id="from_rm_quantity"
                            placeholder="Enter  Quantity">

                        <label for="exampleInputEmail1">Product</label>
                        <select class="form-select" id="form_product">
                            <option value=""></option>
                        </select>
                        <label for="form_rm_type">Raw Material type</label>
                        <select name="" class="form-select" onchange="rm_type_get_edit(this)" id="form_rm_type">
                            <option selected disabled value="">select rm type</option>
                            <option value="rawmaterial">Raw Material</option>
                            <option value="semi_finished_goods">Semi Finished Product</option>
                        </select>
                        <label for="form_rm_id">Raw Material</label>
                        <select class="form-select" id="form_rm_id">
                            <option value="">select Raw Material</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary" id="BillofMaterialButton">Submit</button>
            </div>
        </div>
    </div>
</div>
<div id="billofmaterialsdata">
</div>
<div id="submit_bom"></div>
<script src="{% static 'script/dm/billofmaterial.js' %}"></script>

templates/dmtemplates/parties.html
{% extends 'base/base.html' %}
{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'styles/base.css' %}">
{% endblock %}
{% block content%}
<button type="button" class="btn btn-primary float-end m-5 m-lg-2" onclick="get_add_party()" data-toggle="modal" 
data-target="#partiesModal">
    Add Party
</button>

<!-- Modal -->
<div class="modal fade" id="partiesModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Add Party</h5>
                <button type="button" class="close btn bg-none" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="messages d-flex justify-content-center"></div>
                <div class="justify-content-center">
                    {% csrf_token %}
                    <div class="form-group justify-content-between d-flex">
                        <div>
                            <label for="">Party name</label>
                            <input type="text" class="form-control my-3" id="id_party_name" placeholder="Enter name">
                            <label for="">Party address</label>
                            <input type="text" class="form-control my-3" id="id_party_address"
                                placeholder="Enter address">
                            <label for="">Party state</label>
                            <input type="text" class="form-control my-3" id="id_party_state" placeholder="Enter state">
                            <label for="">Party pincode</label>
                            <input type="text" class="form-control my-3" id="id_party_pincode"
                                placeholder="Enter pincode">

                            <label for="">Party type</label>
                            <select oninput="party_type_change()" class="form-control my-3" id="id_party_type">
                                <option></option>
                            </select>
                            <label for="id_party_products">Party products</label>
                            <div class="d-flex flex-wrap w-75">

                                <select class="form-control my-3" id="id_party_products">
                                    <option value=""></option>

                                </select>
                                <button class="btn btn-primary btn-sm" onclick="AddPart()"> add part</button>
                            </div>
                        </div>
                        <div>

                            <label for="">Party contact name</label>
                            <input type="text" class="form-control my-3" id="id_party_contact_name"
                                placeholder="Enter contact name">
                            <label for="">Party contact no</label>
                            <input type="text" class="form-control my-3" id="id_party_contact_no"
                                placeholder="Enter contact no">
                            <label for="">Party email</label>
                            <input type="text" class="form-control my-3" id="id_party_email" placeholder="Enter email">
                            <label for="">Party country</label>
                            <select class="form-control my-3" id="id_party_country">
                                <option></option>
                            </select>
                            <label for="">Party GSTIN</label>
                            <input type="text" class="form-control my-3" id="id_party_GSTIN" placeholder="Enter gst">
                        </div>
                    </div>
                    <div id="party_product_error"></div>
                    <div id="party_products" class="d-flex flex-wrap"></div>

                
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary" id="Partiesbtn">Submit</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Delete</h5>
                <button type="button" class="close btn bg-none" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Are your sure to delete ?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="yes">Yes</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
            </div>
        </div>
    </div>
</div>
<script src="{% static 'script/dm/parties.js' %}"></script>
<div id="partiesdata" class="overflow-auto">

</div>
{% endblock %}

templates/dmtemplates/product.html
{% extends 'base/base.html' %}

{% block content %}
{% load static %}

<!-- <button onclick=add_product_show() data-target="#productModal" data-toggle="modal"
    class="btn btn-sm btn-primary float-end mx-5">Add
    Product</button>
 -->

<div class="master-data-container">
    {% include 'base/title-header.html' %}
    {% include 'base/navbar.html' %}
    <div class="table-content">
        {% csrf_token %}
        <div class="messages" id="messages"></div>

        <div class="dm-filter">
            <div class="input-group">
                <span class="input-group-append">
                    <button class="btn btn-outline-secondary bg-white border-start-0 border-bottom-0 border ms-n5"
                        type="button">
                        <i class="fa fa-search"></i>
                    </button>
                </span>
                <input class="form-control border-end-0 border" oninput="filter_data(this)" name="filter-search"
                    id="filter-search" type="search">
            </div>
        </div>

        <div class="model-container">

            <div class="form-head">Add Product</div>
            <div class="model-messages"></div>
            <div id="productModal" class="dm-form-body" onchange=check_allfilled(this,6)>

                <div class="form-group">
                    <label for="products_name">Product Name</label>
                    <input type="text" class="form-control" name="" id="products_name">
                </div>
                <div class="form-group">
                    <label for="products_type">Product Type</label>
                    <select name="" class="form-select" id="products_type">
                        <option value="finished">finished</option>
                        <option value="semi_finished">semi_finished</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="min_price">Minimum Price</label>
                    <div class="input-group">
                        <select id="form_currency">
                        </select>
                        <input type="number" class="form-control" name="" id="min_price">
                    </div>
                </div>
                <div class="form-group">

                    <label for="max_price">Max Price</label>
                    <select name="" id="form_currency">
                        <option value=''>---------</option>
                    </select>
                    <input type="number" class="form-control" name="" id="max_price">
                </div>
                <div class="form-group">
                    <label for="form_currency">Currency</label>
                    <select name="" class="form-select" id="form_currency">
                        <option value=''>---------</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="minimum_stock">Minimum Stock</label>
                    <input type="number" class="form-control" name="" id="minimum_stock">
                </div>
                <div class="form-group" id="multipart-form-div">
                </div>
                <!-- <div class="form-group">
                    <p id="add_part-div" style="display: none;"> <input type="text" class="form-control" name=""
                            id="parts" placeholder="part">
                        <span>add parts</span> <button onclick=add_parts(this)><i class="bi bi-plus"></i></button>
                    </p>
                </div> -->


                <p class="product-messages"></p>
                <p class="parts-list"></p>
            </div>
        </div>

        <div class="product-container"></div>
        <div class="fr">

        </div>
        <div class="delete-model-container">
            <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="exampleModalLabel"
                aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Delete</h5>
                            <button type="button" class="close btn bg-none" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            Are your sure to delete ?
                            <div id="delete-error"></div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-primary" data-dismiss="modal" id="yes">Yes</button>
                            <button type="button" class="btn btn-secondary" data-dismiss="modal" id="no">No</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>





{% csrf_token %}

<!-- <button type="submit" class="btn btn-primary" data-dismiss="modal" disabled id="productButton">Submit</button> -->

<script src="{% static 'script/dm/products.js' %}"></script>
{% endblock %}

templates/dmtemplates/productionflow.html
{% extends 'base/base.html' %}
{% block content %}
{% load static %}

<div class="product-default-container">
    {% csrf_token %}
    <div class="messsage"></div>


    <div class="pf-cards-group">
        <div class="pf-cards" onclick='new_pf()'>
            New
        </div>


        <div class="pf-cards" onclick="crud_pf('edit')">
            Edit Existing
        </div>
        <div class="pf-cards" onclick="crud_pf('delete')">
            Delete Existing
        </div>
    </div>
</div>
<p id="product_div"> <label for="form_product">Product</label> <select name="form_product" onchange="get_part(this)"
        id="form_product">
        <option value="">select Product</option>
    </select></p>
<p id="part_div"> <label for="form_product">Part</label> <select name="form_parts" id="form_parts">
        <option value="">select part</option>
    </select></p>
<div class="pf-product-div"></div>
<div class="messages"></div>
<div class="pf-container"></div>
<div class="pf-form"></div>
{% csrf_token %}
<button type="submit" class="btn btn-primary" id="pf_submit" onclick="pf_post()">Submit</button>


<script src="{% static 'script/dm/production_flow.js' %}"></script>
<script src="{% static 'script/dm/pf_edit.js' %}"></script>

<!-- <script src="{% static 'script/production_flow_edit.js' %}"></script> -->

{% endblock %}

templates/dmtemplates/rawmaterials.html
{% extends 'base/base.html' %}
{% load static %}
{% block content%}
<button type="button" class="btn btn-primary float-end m-5" onclick=show_rm() data-toggle="modal"
    data-target="#RawmaterialsModal">
    Add Raw Matrial
</button>

<!-- Modal -->
<div class="modal fade" id="RawmaterialsModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Add Raw Material</h5>
                <button type="button" class="close btn bg-none" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="messages"></div>
                <div class="d-flex flex-row justify-content-center">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="exampleInputEmail1">Raw Material</label>
                        <input type="text" class="form-control my-3" id="id_rm_name" placeholder="Enter Material">
                        <label for="exampleInputEmail1">Unit</label>
                        <select name="" class="form-select" id="id_measured_unit">
                            <option value=''>---------</option>
                        </select>
                        <!-- <input type="text" class="form-control my-3" id="id_measured_unit" placeholder="Enter Unit"> -->
                        <label for="exampleInputEmail1">Stock</label>
                        <input type="text" class="form-control my-3" id="id_min_stock" placeholder="Enter Stock">
                        <label for="exampleInputEmail1">Price</label>
                        <input type="text" class="form-control my-3" id="id_rm_max_price" placeholder="Enter Price">
                        <label for="exampleInputEmail1">Currency</label>
                        <select name="" class="form-select" id="id_currency">
                            <option value=''>---------</option>
                        </select>
                        <label for="exampleInputEmail1">Prefered Party</label>
                        <select class="form-control my-3" id="id_preferred_supplier_id">
                            <option value=""></option>
                        </select>


                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary" id="RawMaterialButton">Submit</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Delete</h5>
                <button type="button" class="close btn bg-none" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Are your sure to delete ?
                <div class="error-delete"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="yes">Yes</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
            </div>
        </div>
    </div>
</div>
<script src="{% static 'script/dm/rawmaterials.js' %}"></script>
<div id="rawmaterialsdata">

</div>
{% endblock %}