erp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('accounts.urls')),
    path('api/', include('data_management.urls')),
    path('api/', include('inventory_management.urls')),
    path('api/', include('sales_management.urls')),
    path('api/',include('purchase_management.urls')),
    path('', include('frontend.frontendurls'))
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import MinLengthValidator, MaxValueValidator
from django.core.exceptions import ValidationError
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.contrib.auth.hashers import make_password
from django.http import JsonResponse
from django.core.management.base import BaseCommand, CommandError
import uuid
from data_management.models import Country
# Create your models here.

from django.contrib.auth.management.commands import createsuperuser


class Branch(models.Model):
    id = models.AutoField(primary_key=True)
    cityname = models.CharField( max_length=50, null=True, blank=True)
    state = models.CharField(max_length=30, default='TamilNadu')
    country = models.ForeignKey(
        Country, on_delete=models.SET_NULL, null=True, blank=True)
    pincode = models.IntegerField(default=6000007)
    GST_Number = models.CharField(unique=True, blank=True, max_length=30)
    branch_code = models.CharField(
        editable=False, unique=True, max_length=10, null=True, blank=True, default='branchcode')
    branch_name = models.CharField(
        max_length=30, unique=True, null=True, blank=True)
    address = models.CharField(
        max_length=50, unique=True, null=True, blank=True)

    def save(self, *args, **kwargs):
        self.branch_code = str(uuid.uuid4())[:6]
        return super(Branch, self).save(*args, **kwargs)

    def __str__(self):
        return self.branch_name


class Department(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(unique=True, max_length=50)
    role = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.name


class Sub_division(models.Model):
    id = models.AutoField(primary_key=True)
    department = models.ForeignKey(
        Department, null=True, on_delete=models.SET_NULL)
    name = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.name


class UserRole(models.Model):
    id = models.AutoField(primary_key=True)
    department = models.ForeignKey(
        Department, null=True, blank=True, on_delete=models.SET_NULL)
    role = models.CharField(max_length=30, unique=True)
    division = models.ForeignKey(
        Sub_division, null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.role


class MyUserManager(BaseUserManager):
    def create_user(self, employee_id, password, name, **extra_fields):
        phone = extra_fields.get('phone', None)
        department_id = extra_fields.get('department', None)
        sub_division = extra_fields.get('department_subdivision', None)
        role = extra_fields.get('role', None)
        email = extra_fields.get('email', None)
        # employee_id = extra_fields.get('id', None)
        # name = extra_fields.get('name', None)
        if phone:
            try:
                phone = int(phone)
            except:
                raise ValueError('Mobile number only number')
        # password = make_password(password)
        # self.set_password(self.password)
        user = self.model(name=name, department=department_id, email=email,
                          phone=phone, employee_id=employee_id, department_subdivision=sub_division, role=role)
        # print(user)
        print(password)
        user.set_password(password)
        # user.save(using=self._db)
        return user

    def create_superuser(self, **extra_fields):
        user = self.create_user(**extra_fields)
        user.is_superuser = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    email = models.EmailField(unique=True, null=True, blank=True)
    employee_id = models.CharField(
        unique=True, null=False, primary_key=True, max_length=50, default=123, blank=True)
    name = models.CharField(unique=True, max_length=50)
    phone = models.CharField(
        default=1234567890,
        max_length=10,
        validators=[
            MinLengthValidator(10)
        ], null=True, blank=True)
    department = models.ForeignKey(
        Department, on_delete=models.SET_NULL, null=True, blank=True)
    department_subdivision = models.ForeignKey(
        Sub_division, on_delete=models.SET_NULL, null=True, blank=True)
    role = models.ForeignKey(UserRole, on_delete=models.SET_NULL, null=True)
    is_superuser = models.BooleanField(default=False)
    reset_password = models.BooleanField(default=True)
    branch = models.ForeignKey(Branch, on_delete=models.SET_NULL, null=True)
    created_at = models.DateTimeField(default=timezone.now)
    objects = MyUserManager()
    USERNAME_FIELD = 'employee_id'
    REQUIRED_FIELDS = ['name', 'password']

    def save(self, *args, **kwargs):
        return super(User, self).save(*args, **kwargs)

    def __str__(self):
        return self.employee_id

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        return True

    @ property
    def is_staff(self):
        return self.is_superuser

    class Meta:
        ordering = ('created_at',)

data_management/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField
from django.core.exceptions import ValidationError
# from pos
# Create your models here.


class MeasuredUnits(models.Model):
    measured_unit_code = models.CharField(
        max_length=30, primary_key=True, default='id')

    measured_unit_name = models.CharField(max_length=30, unique=True)

    def __str__(self) -> str:
        return self.measured_unit_name

    def save(self, *args, **kwargs):
        self.measured_unit_name = self.measured_unit_name .lower()
        super(MeasuredUnits, self).save(*args, **kwargs)


class Currency(models.Model):
    currency_code = models.CharField(
        max_length=30, primary_key=True, default='id')
    currency_name = models.CharField(max_length=30, unique=True)

    def __str__(self) -> str:
        return self.currency_name

    def save(self, *args, **kwargs):
        self.currency_name = self.currency_name.lower()
        super(Currency, self).save(*args, **kwargs)


class PartyType(models.Model):
    party_type = models.CharField(max_length=30, unique=True)

    class Meta:
        verbose_name = "PartyType"

    def __str__(self) -> str:
        return self.party_type

    def save(self, *args, **kwargs):
        self.party_type = self.party_type.lower()
        super(PartyType, self).save(*args, **kwargs)


class Country(models.Model):
    country_code = models.CharField(
        max_length=30, primary_key=True, default='id')
    country_name = models.CharField(max_length=30, unique=True)

    class Meta:
        verbose_name = "Country"

    def __str__(self) -> str:
        return self.country_name

    def save(self, *args, **kwargs):
        self.country_name = self.country_name.lower()
        super(Country, self).save(*args, **kwargs)


class State(models.Model):
    state_code = models.CharField(
        max_length=30, primary_key=True, default='id')
    state_name = models.CharField(max_length=30, null=True, blank=True)
    GST_code = models.CharField(max_length=30, null=True, blank=True)

    def __str__(self) -> str:
        return self.state_name


class Parties(models.Model):
    id = models.AutoField(primary_key=True)
    party_type = models.ForeignKey(
        PartyType, to_field='party_type', on_delete=models.SET_NULL, null=True)
    party_country = models.ForeignKey(
        Country, on_delete=models.SET_NULL, null=True)
    party_name = models.CharField(max_length=50)
    party_address = models.TextField()
    party_state = models.ForeignKey(
        State, on_delete=models.SET_NULL, null=True)
    party_pincode = models.IntegerField()
    party_GSTIN = models.CharField(max_length=30, null=True, blank=True)
    party_products = models.JSONField(null=True, blank=True)
    party_contact_name = models.CharField(max_length=30, null=True, blank=True)
    party_contact_no = models.CharField(max_length=30, null=True, blank=True)
    party_email = models.CharField(max_length=30, null=True, blank=True)

    class Meta:
        verbose_name = "Party"

    def clean(self):
        parties = Parties.objects.filter(
            party_name__iexact=self.party_name.lower())
        if self.pk:
            parties = parties.exclude(pk=self.pk)
        if parties.exists():
            raise ValidationError("This party already exists.")

    def __str__(self) -> str:
        return self.party_name


product_type_choices = [('finished', 'finished'),
                        ('semi-finished', 'semi-finished'),]
rm_type_choices = [('semi_finished_goods', 'semi_finished_goods'),
                   ('rawmaterial', 'Rawmaterial'),]


class ProductionPhases(models.Model):
    id = models.AutoField(primary_key=True)
    phase_name = models.CharField(max_length=100, unique=True)

    class Meta:
        verbose_name = "ProductionPhase"
        db_table = 'ProductionPhase'

    def __str__(self) -> str:
        return self.phase_name

    def save(self, *args, **kwargs):
        self.phase_name = self.phase_name.lower()
        super(ProductionPhases, self).save(*args, **kwargs)


class Product(models.Model):
    product_code = models.CharField(
        unique=True, primary_key=True, max_length=50, default='id')
    product_name = models.CharField(unique=True, max_length=100)
    product_type = models.CharField(
        max_length=50, choices=product_type_choices, default='finished')
    min_stock = models.IntegerField(default=100)
    maximum_price = models.IntegerField()
    minimum_price = models.IntegerField()
    currency = models.ForeignKey(
        Currency, on_delete=models.SET_NULL, null=True, blank=True)
    multiple_parts = models.BooleanField(default=False)
    parts = ArrayField(
        models.CharField(max_length=50, blank=True),
        blank=True,
        default=list,
        null=True
    )

    class Meta:
        verbose_name = "Product"

    def __str__(self) -> str:
        return self.product_name


class Rawmaterials(models.Model):
    rm_code = models.CharField(max_length=30, primary_key=True,)
    rm_name = models.CharField(max_length=50)
    measured_unit = models.ForeignKey(
        MeasuredUnits, on_delete=models.SET_NULL, null=True, blank=True)
    min_stock = models.IntegerField()
    rm_max_price = models.IntegerField()
    currency = models.ForeignKey(
        Currency, on_delete=models.SET_NULL, null=True, blank=True)
    preferred_supplier = ArrayField(
        models.CharField(max_length=30, null=True, blank=True),
        default=list
    )

    class Meta:
        verbose_name = "Rawmaterial"

    def __str__(self) -> str:
        return self.rm_name


class BillOfMaterials(models.Model):
    id = models.AutoField(primary_key=True)
    product_code = models.ForeignKey(Product, on_delete=models.CASCADE)
    part_name = models.CharField(max_length=30, null=True, blank=True)
    rm_serial_no = models.IntegerField(unique=True, null=True, blank=True)
    rm_type = models.CharField(
        max_length=20, choices=rm_type_choices, default='rawmaterial')
    rm_code = models.CharField(max_length=50,null=True, blank=True)
    rm_name = models.CharField(max_length=50)
    rm_quantity = models.IntegerField(null=True, blank=True)
    production_phase = models.ForeignKey(
        ProductionPhases, on_delete=models.SET_NULL, null=True, blank=True)
    measured_unit = models.ForeignKey(
        MeasuredUnits, on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        verbose_name = "BillOfMaterial"

    def save(self, *args, **kwargs):
        try:
            if self.rm_type == 'rawmaterial':
                rm = Rawmaterials.objects.get(pk=self.rm_code)
                self.rm_name = rm.rm_name
                if rm and rm.measured_unit:
                    self.measured_unit = rm.measured_unit
            else:
                rm = Product.objects.get(
                    pk=self.rm_code)
                self.rm_name = rm.product_name
        except Exception as error:
            raise ValidationError(error)
        return super(BillOfMaterials, self).save(*args, **kwargs)

    def __str__(self) -> str:
        return self.product_code.product_name + '-' + self.rm_name


class ProductionFlow(models.Model):
    id = models.AutoField(primary_key=True)
    product_code = models.ForeignKey(Product, on_delete=models.CASCADE)
    part_name = models.CharField(max_length=50, null=True, blank=True)
    phases = models.JSONField(null=True, blank=True)

    class Meta:
        verbose_name = "ProductionFlow"

    def __str__(self) -> str:
        return self.part_name


class Productivity(models.Model):
    id = models.AutoField(primary_key=True)
    phase = models.ForeignKey(
        ProductionPhases, on_delete=models.SET_NULL, null=True, blank=True)
    product = models.ForeignKey(
        Product, on_delete=models.SET_NULL, null=True, blank=True)
    part_name = models.CharField(max_length=50, null=True, blank=True)
    quantity_perday = models.PositiveIntegerField()
    scrap_quantity = models.CharField(max_length=30, null=True, blank=True)

    def __str__(self) -> str:
        return str(self.quantity_perday)

templates/backup/branch.html
{% extends 'base/base.html' %}
{% load static %}
{% block styles %}
<link rel="stylesheet" href="">
{% endblock %}

{% block content %}
<!-- Button trigger modal -->
<button type="button" class="btn btn-sm btn-primary float-end m-5" data-toggle="modal" data-target="#branchModal"
  onclick="add_branch_show()">
  Add Branch
</button>

<div class="modal fade" id="branchModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add Branch</h5>
        <button type="button" class="close btn bg-none" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body text-center">
        <div class="messages"></div>
        {% csrf_token %}
        <input type="text" class="form-control my-3" id="id_branch_name" placeholder="branch_name">
        <input type="text" class="form-control my-3" id="id_branch_cityname" placeholder="city_name">
        <input type="text" class="form-control my-3" id="id_branch_state" placeholder="state">
        <label for="form_country">country</label> <select name="" class="form_country" id="id_branch_country"></select>
        <input type="number" class="form-control my-3" id="id_branch_pincode" placeholder="pincode">
        <input type="text" class="form-control my-3" id="id_branch_gstnumber" placeholder="GST_Number">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary" id="branchButton">Submit</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Delete</h5>
        <button type="button" class="close btn bg-none" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Are your sure to delete ?
        <div id="delete-error"></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" id="yes">Yes</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
      </div>
    </div>
  </div>
</div>
<div class="branch-main" id="branch-main"></div>
<script src="{% static 'script/branch.js' %}"></script>

{% endblock %}

templates/backup/country.html
{% extends 'base/base.html' %}
{% load static %}
{% block content%}
<button type="button" class="btn btn-primary float-end m-5" data-toggle="modal" data-target="#countryModal">
    Add Country
</button>

<!-- Modal -->
<div class="modal fade" id="countryModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Add Country</h5>
                <button type="button" class="close btn bg-none" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="messages"></div>
                <div class="d-flex flex-row justify-content-center">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="">Country</label>
                        <input type="text" class="form-control my-3" id="id_country_name" placeholder="Enter partytype">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary" id="Countrybtn">Submit</button>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Delete</h5>
                <button type="button" class="close btn bg-none" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Are your sure to delete ?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="yes">Yes</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
            </div>
        </div>
    </div>
</div>
<script src="{% static 'script/country.js' %}"></script>
<div id="partytypedata">

</div>
{% endblock %}

templates/backup/department.html
{% extends 'base/base.html' %}
<!-- {% load static %} -->
{% block content %}
<div class="department-main">
  <div class="branch-main"></div>
  <button type="button" class="btn btn-sm btn-primary float-end m-5" data-toggle="modal" data-target="#deptModal"
    onclick="add_dept()">
    Add Department
  </button>
  <div class="department-container">
  </div>
</div>

<div class="modal fade" id="deptModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add Department</h5>
        <button type="button" class="close btn bg-none" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body text-center">
        <div class="messages"></div>
        {% csrf_token %}
        <input type="text" class="form-control my-3" id="dept_name" placeholder="department name">
        <!-- <input type="text" class="form-control my-3" id="subdivision" placeholder="subdivision"> -->
        <input type="text" class="form-control my-3" id="dept_role" placeholder="role">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary" id="deptButton">Submit</button>
      </div>
    </div>
  </div>
</div>

<!-- <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Delete</h5>
        <button type="button" class="close btn bg-none" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div id="delete-error"></div>
        Are your sure to delete ?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" id="yes">Yes</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
      </div>
    </div>
  </div>
</div> -->

<script src="{% static 'script/department.js' %}"></script>
{% endblock %}

{% block styles %}
{% endblock %}

templates/backup/dropdownproduct.html
<option value="">---------</option>
{% for item in items %}
<option value="{{ item.id }}">{{ item.product }}</option>
{% endfor %}

templates/backup/party type.html
{% extends 'base/base.html' %}
{% load static %}
{% block content%}
<button type="button" class="btn btn-primary float-end m-5" data-toggle="modal" data-target="#partiestypeModal">
    Add Party Type
</button>

<!-- Modal -->
<div class="modal fade" id="partiestypeModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Add Party Type</h5>
                <button type="button" class="close btn bg-none" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="messages"></div>
                <div class="d-flex flex-row justify-content-center">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="">Party type</label>
                        <input type="text" class="form-control my-3" id="id_partytype_name"
                            placeholder="Enter partytype">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary" id="Partiestypebtn">Submit</button>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Delete</h5>
                <button type="button" class="close btn bg-none" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Are your sure to delete ?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="yes">Yes</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
            </div>
        </div>
    </div>
</div>
<script src="{% static 'script/partytype.js' %}"></script>
<div id="partytypedata">

</div>
{% endblock %}

templates/backup/phase.html
{% extends 'base/base.html' %}
{% load static %}
{% block styles %}
<link rel="stylesheet" href="">
{% endblock %}

{% block content %}
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary float-end m-5" data-toggle="modal" data-target="#phaseModal">
  Add Phase
</button>

<!-- Modal -->
<div class="modal fade" id="phaseModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add phase</h5>
        <button type="button" class="close btn bg-none" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="messages"></div>
        <div class="d-flex flex-row justify-content-center">
          {% csrf_token %}
          <div class="form-group">
            <label for="exampleInputEmail1">Phase</label>
            <input type="text" class="form-control my-3" id="phase" placeholder="Enter phase">

          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary" id="phaseButton">Submit</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Delete</h5>
        <button type="button" class="close btn bg-none" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="error-delete"></div>
        Are your sure to delete ?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" id="yes">Yes</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
      </div>
    </div>
  </div>
</div>

<script src="{% static 'script/phase.js' %}"></script>
<div id="phasedata">

</div>
{% endblock %}

templates/backup/production_flow.html
{% extends 'base/base.html' %}
{% block content %}
{% load static %}


<div class="product-default-container">
    {% csrf_token %}
    <div class="messsage"></div>
    <p> <label for="form_product">Product</label> <select name="form_product" id="form_product">
            <option value="">select Product</option>

    <div class="pf-cards-group">
        <div class="pf-cards" onclick='postgetpf()'>
            New
        </div>

        <div class="pf-cards" onclick=edit_get_pf()>
            Edit Existing
        </div>
        <div class="pf-cards" onclick=delete_get_pf()>
            Delete Existing
        </div>
    </div>
</div>
<p id="part_div"> <label for="form_product">Part</label> <select name="form_parts" id="form_parts">
        <option value="">select part</option>
    </select></p>
<div class="messages"></div>
<div class="pf-container"></div>
<div class="pf-form"></div>

{% csrf_token %}
<button type="submit" class="btn btn-primary" id="pf_submit" onclick="pf_post()">Submit</button>

<!-- <button class="btn btn-sm btn-primary float-end mx-5" onclick=show_pf() data-toggle="modal"
    data-target="#productionflowModal">Add
    ProductionFlow</button> -->


<div class="modal fade" id="productionflowModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Add ProductionFlow</h5>
                <button type="button" class="close btn bg-none" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body text-center">
                <!-- onchange=check_allfilled(this,6) -->
                {% csrf_token %}
                <label for="id_product">Product</label>
                <select class="form-control m-1" name="" id="id_product">
                    <option value=""></option>
                </select>
                <label for="id_partname">Part</label>
                <select class="form-control m-1" name="" id="id_part_name">
                    <option value=""></option>
                </select>
                <label for="id_phase">Phase</label>
                <select class="form-control m-1" name="" id="id_phases">
                    <option value=""></option>
                </select>
                <button type="submit" class="btn btn-primary" onclick=AddPhase()>Add Phase</button>

                <p class="messages"></p>
                <p class="pf-list"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary" onclick=AddProductionflow(null)
                    id="productflowButton">Submit</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Delete</h5>
                <button type="button" class="close btn bg-none" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Are your sure to delete ?
                <div class="error-delete"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="yes">Yes</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
            </div>
        </div>
    </div>
</div>
<div id="productionflowdata"></div>
<script src="{% static 'script/production_flow.js' %}"></script>
<script src="{% static 'script/production_flow_edit.js' %}"></script>

{% endblock %}